# Generated by Django 3.1.4 on 2021-01-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SKSApp', '0002_auto_20210117_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='scriptlangs',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SKSApp.scripttypes'),
        ),
    ]
