# Generated by Django 3.1.4 on 2021-01-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptlangs',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
