# Generated by Django 3.1.4 on 2021-01-17 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptLangs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.TextField()),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptLangsAdd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.TextField()),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SKSApp.scriptlangs')),
            ],
        ),
    ]
